# Generated by Django 2.2.5 on 2019-10-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
