# Generated by Django 2.2.5 on 2019-10-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0002_posts_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(default='Lorenzo', on_delete=django.db.models.deletion.CASCADE, to='hackapp.Users'),
        ),
    ]
